# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_clientprovision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IceDam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('treated', models.IntegerField(choices=[(1, 'Nothing done'), (2, 'Drone left CaCl'), (3, 'Power washed off roof'), (4, 'Picked off roof manually'), (5, 'Other treatment')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('drone_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_operator', to='users.DroneOperator')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taken', models.DateTimeField(auto_now_add=True)),
                ('image_type', models.IntegerField(choices=[(1, 'Not specified'), (2, 'RGB Image'), (3, 'Thermal Image')], default=1)),
                ('link', models.URLField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Inspection')),
            ],
        ),
        migrations.AddField(
            model_name='icedam',
            name='inspection_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.InspectionImage'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='inspection_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.InspectionImage'),
        ),
    ]
