# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_client', to='users.Client'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='drone_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DroneOperator'),
        ),
    ]
