# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20160223_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Inspection')),
            ],
        ),
    ]
