# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectionprovision'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionImageProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'Not specified'), (2, 'Roof Edge Image'), (3, 'Thermal Image'), (4, 'Aerial Image')], default=1),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='taken',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='inspectionimageprovision',
            name='inspection_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.InspectionImage'),
        ),
    ]
