# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_auto_20160302_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionimage',
            name='link',
        ),
        migrations.AddField(
            model_name='inspectionimage',
            name='path',
            field=models.TextField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
