# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_auto_20160331_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionimage',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_image', to='inspections.Inspection'),
        ),
    ]
