# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneoperator',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not specified'), (2, 'Email Confirmed'), (3, 'Deleted')], default=1),
        ),
    ]
