# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprovision'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unique_code', models.TextField()),
                ('unique_url', models.TextField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('drone_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DroneOperator')),
            ],
        ),
    ]
